# Generated by Django 5.0.6 on 2024-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='access',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='demo_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_previews/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='use_cases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
