# Generated by Django 5.0.6 on 2024-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0003_alter_agent_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='accessory_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pricing_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
