# Generated by Django 5.0.6 on 2024-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0006_agent_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='pricing_model',
            new_name='pricing',
        ),
    ]
