# Generated by Django 5.0.6 on 2024-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0007_rename_pricing_model_agent_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
