# Generated by Django 5.0.6 on 2024-09-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0008_alter_agent_description_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
