# Generated by Django 5.0.6 on 2024-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0009_agent_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
