# Generated by Django 5.0.6 on 2024-09-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi_agents_app', '0010_alter_agent_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
